from django.contrib import admin
from .models import *

admin.site.register(Notificacao)
admin.site.register(Cidade)
admin.site.register(Servico)
admin.site.register(Sub_categoria)
admin.site.register(Comentario_servico)
admin.site.register(Tipo_contato)
admin.site.register(Contato)
admin.site.register(Avaliacao_servico)
admin.site.register(Categoria)
admin.site.register(Estabelecimeto)
admin.site.register(Usuario)
admin.site.register(Endereco)
admin.site.register(Avaliacao_estabelecimento)
admin.site.register(Comentario_estabelecimento)
admin.site.register(Imagens)
admin.site.register(Usuario_le_notificacao)
admin.site.register(Usuario_segue_ser)
admin.site.register(Usuario_cadastra_ser)
admin.site.register(Usuario_cria_notificacao)
admin.site.register(Cadastro_contato)
admin.site.register(Realiza_avaliacao_ser)
admin.site.register(Faz_comentario_ser)
admin.site.register(Comentario_sobre_ser)
admin.site.register(Avaliacao_sobre_ser)
admin.site.register(Cidade_endereco)
admin.site.register(Servico_sub_categoria)
admin.site.register(Comenta_sobre_est)
admin.site.register(Faz_comentario_est)
admin.site.register(Realiza_avaliacao_est)
admin.site.register(Avalia_local)
admin.site.register(Usuario_cidade)
admin.site.register(Fale_conosco)